sb_gemv – structblas
sb_gemv Interface
3 statements
Source File
public interface sb_gemv
Calls
Called by
Contents
Module Procedures
d_circ_gemv
Module Procedures
public subroutine d_circ_gemv(trans, alpha, circm, x, beta, y, planf, planb)
Computes or
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: trans
real(kind=real64), intent(in) :: alpha
type(dcirculant), intent(inout) :: circm
real(kind=real64), intent(inout), dimension(:) :: x
real(kind=real64), intent(in) :: beta
real(kind=real64), intent(inout), dimension(:) :: y
type(c_ptr), intent(inout), optional :: planf
type(c_ptr), intent(inout), optional :: planb
Call graph
sb_gemv calls d_circ_gemv
d_circ_gemv calls fftw_plan_dft_r2c_1d, fftw_execute_dft_r2c, fftw_plan_dft_c2r_1d, fftw_execute_dft_c2r, sb_toupper
test_dgemv calls sb_gemv