d_circ_gemv – structblas
d_circ_gemv Subroutine
80 statements
Source File
public subroutine d_circ_gemv(trans, alpha, circm, x, beta, y, planf, planb)
Uses
iso_fortran_env
iso_c_binding
structblas_const_mod
fftw_mod
structblas_util_mod
Computes or
Passing a fftw plan to this routine is useful for repeated matrix-vector products if you pass it, and the plan is not associated to something after the first matrix vector product the plan is created and can be reused
The function checks in case of quick returns: or .
If trans = 'T' then
If trans = 'N' then
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: trans
real(kind=real64), intent(in) :: alpha
type(dcirculant), intent(inout) :: circm
real(kind=real64), intent(inout), dimension(:) :: x
real(kind=real64), intent(in) :: beta
real(kind=real64), intent(inout), dimension(:) :: y
type(c_ptr), intent(inout), optional :: planf
type(c_ptr), intent(inout), optional :: planb
Calls
Called by
Contents
None
Call graph
d_circ_gemv calls sb_toupper, fftw_execute_dft_r2c, fftw_plan_dft_c2r_1d, fftw_execute_dft_c2r, fftw_plan_dft_r2c_1d
sb_gemv calls d_circ_gemv
test_dgemv_1 calls sb_gemv
test_dgemv_2 calls sb_gemv