sb_toupper – structblas
sb_toupper Function
13 statements
Source File
public pure function sb_toupper(str) result(string)
Changes a string to upper case
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: str
Return Value character
Called by
Contents
Source Code
sb_toupper
Source Code
pure Function sb_toupper (str) result(string)
!! Changes a string to upper case
    implicit None
    character(*), Intent(In) :: str
    character(LEN(str))      :: string
    integer :: ic, i
    character(26), Parameter :: cap = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    character(26), Parameter :: low = 'abcdefghijklmnopqrstuvwxyz'
!   Capitalize each letter if it is lowecase
    string = str
    do i = 1, LEN_TRIM(str)
        ic = INDEX(low, str(i:i))
        if (ic > 0) string(i:i) = cap(ic:ic)
    end do
end function sb_toupper
Call graph
d_circ_gemv calls sb_toupper
sb_gemv calls d_circ_gemv
test_dgemv_1 calls sb_gemv
test_dgemv_2 calls sb_gemv