test_dgemv_1 – structblas
test_dgemv_1 Subroutine
73 statements
Source File
subroutine test_dgemv_1()
Test dgemv for the matrix-vector multiplication
Arguments
None
Calls
Contents
Variables
alpha beta c1 controlmat cvec i info j mat n normfroerr x y z
Source Code
test_dgemv_1
Variables
Type Visibility Attributes Name Initial
real(kind=real64), public :: alpha
real(kind=real64), public :: beta
type(dcirculant), public :: c1
real(kind=real64), public, dimension(:,:), allocatable :: controlmat
real(kind=real64), public, dimension(:), allocatable :: cvec
integer(kind=int32), public :: i
integer(kind=int32), public :: info
integer(kind=int32), public :: j
real(kind=real64), public, dimension(:,:), allocatable :: mat
integer(kind=int32), public :: n
real(kind=real32), public :: normfroerr
real(kind=real64), public, dimension(:), allocatable :: x
real(kind=real64), public, dimension(:), allocatable :: y
real(kind=real64), public, dimension(:), allocatable :: z
Source Code
        subroutine test_dgemv_1()
            !! Test `dgemv` for the matrix-vector multiplication
            implicit none
            type(dcirculant) :: c1
            real(kind=real64) :: alpha, beta
            real(kind=real64), dimension(:), allocatable :: cvec,x,y,z
            real(kind=real64), dimension(:,:), allocatable :: mat,controlmat
            real(kind=real32) :: normfroerr
            integer(kind=int32) :: info,n,i,j
            n = 20
            allocate(cvec(2),stat=info)
            call check(is_equal(info,0), msg="cvec allocate failed")
            allocate(controlmat(n,n),stat=info)
            call check(is_equal(info,0), msg="controlmat allocate failed")
            allocate(x(n),y(n),z(n),stat=info)
            call check(is_equal(info,0), msg="x/y/z allocate failed")
            call random_number(x)
            call random_number(y)
            call random_number(alpha)
            call random_number(beta)
            do i=1,n
                do j=1,n
                    if (i-j== 1) then
                        controlmat(i,j) = -done
                    else if (i == j) then
                        controlmat(i,j) = done
                    else
                        controlmat(i,j) = dzero
                    end if
                end do
            end do
            controlmat(1,n) = -done
            cvec = [1, -1]
            call c1%setc(cvec,info,n=n)
            call check(is_equal(info, structblas_success_), msg="setc with n failed")
            call check(is_equal(size(c1%c),n), msg="setc%c wrong size")
            call c1%build(info)
            call check(is_equal(info, structblas_success_), msg="build from c failed")
            call check(is_equal(size(c1%lambda),n), msg="setc%lambda wrong size")
            call c1%tomat(mat,info)
            call check(is_equal(info, structblas_success_), msg="tomat failed")
            normfroerr = dzero
            do i=1,n
                do j=1,n
                    normfroerr = normfroerr + (mat(i,j)-controlmat(i,j))**2
                end do
            end do
            normfroerr = sqrt(normfroerr)
            if (normfroerr.le.1d1*epsilon(cvec(1))) then
                info = structblas_success_
            else
                info = structblas_fail_
                write(output_unit,'("(Matrix) Error is ",E16.5)') normfroerr
            end if
            call check(is_equal(info,structblas_success_), msg="wrong matrix reconstruction")
            ! Compute control product
            z = alpha*matmul(mat,x) + beta*y
            ! Compute real product
            call sb_gemv('N', alpha, c1, x, beta, y)
            ! Check the error;
            normfroerr = dzero
            do i=1,n
                normfroerr = normfroerr + (y(i) - z(i))**2
            end do
            normfroerr = sqrt(normfroerr)
            if (normfroerr.le.1d1*epsilon(cvec(1))) then
                info = structblas_success_
            else
                info = structblas_fail_
                write(output_unit,'("(Vector) Error is ",E16.5)') normfroerr
            end if
            call check(is_equal(info,structblas_success_), msg="wrong vector reconstruction")
            deallocate(cvec,controlmat,x,y,z,stat=info)
            call check(is_equal(info,0), msg="deallocate failed")
            call c1%free(info)
            call check(is_equal(info,0), msg="circulant free failed")
        end subroutine test_dgemv_1
Call graph
test_dgemv_1 calls is_equal, sb_gemv, check
sb_gemv calls d_circ_gemv
d_circ_gemv calls sb_toupper, fftw_execute_dft_r2c, fftw_plan_dft_c2r_1d, fftw_execute_dft_c2r, fftw_plan_dft_r2c_1d